<?php
$z[0]=Array("field","",71,99);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",101,130);
$z[1][4]['name']="typename";
$z[2]=Array("field","",166,194);
$z[2][4]['name']="typeurl";
$z[3]=Array("list","   \r\n				    <li>\r\n					    <div class=\"left_logo\"> [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' height='72' width='130'/></a>\"); [/field:array]</div>\r\n						<div class=\"rightcon\">\r\n						    <div class=\"tit\"><a href=\"[field:arcurl/]\"><span class=\"bt\">[field:title/]</span></a><span class=\"date\">[field:pubdate function=\"GetDateTimeMK(@me)\"/]</span></div>\r\n							<div class=\"con\">[field:description/]...</div>\r\n						</div>\r\n					</li>\r\n\r\n<!--                     <li><a class=\"pic\" href=\"#\">\r\n                            <img src=\"images/zhengzhuang.png\" width=\"155\" height=\"160\" border=\"0\" /><span class=\"countdown\">休闲西服01</span></a></li>-->\r\n\r\n					",327,1111);
$z[3][4]['pagesize']="10";

?>