<?php
$z[0]=Array("field","",75,103);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",105,134);
$z[1][4]['name']="typename";
$z[2]=Array("field","",170,198);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","    \r\n                             <li><a href=\"[field:arcurl /]\" class=\"pic\">\r\n                                 <img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\" /><span class=\"countdown\">[field:title /]</span></a>\r\n                             </li>\r\n                            ",340,697);
$z[3][4]['titlelen']="42";
$z[3][4]['row']="10";

?>