<li>
					    <div class="left_logo">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'  width="130" height="72" /></a>"); [/field:array]</div>
						<div class="rightcon">
						    <div class="tit"><span class="bt"> <a href="[field:arcurl/]" class="title">[field:title/]</a></span><span class="date">[field:pubdate function="GetDateTimeMK(@me)"/]</span></div>
							<div class="con">[field:description/]...</div>
						</div>
					</li>