<?php
$z[0]=Array("field","",48,76);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",78,107);
$z[1][4]['name']="typename";
$z[2]=Array("field","",148,176);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n           <li><a href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/></a></li>\r\n		",256,488);
$z[3][4]['row']="3";
$z[3][4]['type']="image.";
$z[4]=Array("arclist","\r\n            <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n			",549,674);
$z[4][4]['titlelen']="60";
$z[4][4]['row']="8";
$z[5]=Array("field","",796,824);
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",826,855);
$z[6][4]['name']="typename";
$z[7]=Array("field","",891,919);
$z[7][4]['name']="typeurl";
$z[8]=Array("arclist","\r\n           <li><a class=\"pic\" href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/><span class=\"countdown\">休闲西服01</span></a></li>\r\n		",1050,1339);
$z[8][4]['row']="4";
$z[8][4]['type']="image.";

?>