<?php
$z[0]=Array("field","",71,99);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",101,130);
$z[1][4]['name']="typename";
$z[2]=Array("field","",166,194);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","    \r\n     <li><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n",324,519);
$z[3][4]['titlelen']="42";
$z[3][4]['row']="10";

?>