<li>

                     <div class="proleftbox">
                                <img src="[field:litpic/]"  width="255" height="175" />
                            </div>
                            <div class="rightinfo">
                                <p class="tit"><a href='[field:arcurl}'>[field:title/]</a></p>
                                <p class="action"><a class="rate" href="#"><s></s>好评： 152</a><a class="popularity" href="#"><s></s>人气：[field:click/]</a></p>
                                <p>价格：[field:trueprice/]元</p>
                                <p class="pre">详情： [field:description/]</p>
                            </div>
				</li>