<li>
					    <div class="left_logo"> [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' height='72'/></a>"); [/field:array]</div>
						<div class="rightcon">
						    <div class="tit"><a href="[field:arcurl/]" class="title"><span class="bt">[field:title/]</span></a><span class="date">[field:pubdate function="GetDateTimeMK(@me)"/]</span></div>
							<div class="con">[field:description/]...</div>
						</div>
					</li>