<?php
$z[0]=Array("include","",561,596);
$z[0][4]['filename']="head.htm";
$z[1]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n ",762,1008);
$z[1][4]['type']="son";
$z[1][4]['row']="10";
$z[1][4]['typeid']="2";
$z[1][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[2]=Array("field","",1385,1407);
$z[2][4]['name']="typename";
$z[3]=Array("field","",1495,1516);
$z[3][4]['name']="content";
$z[4]=Array("include","",1594,1631);
$z[4][4]['filename']="footer.htm";

?>