<?php
$z[0]=Array("field","",71,99);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",101,130);
$z[1][4]['name']="typename";
$z[2]=Array("field","",166,194);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n           <li><a class=\"pic\" href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/><span class=\"countdown\">休闲西服01</span></a></li>\r\n		",329,618);
$z[3][4]['row']="4";
$z[3][4]['type']="image.";
$z[4]=Array("list","   \r\n				    <li>\r\n					    <div class=\"left_logo\"> [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' height='72' width='130'/></a>\"); [/field:array]</div>\r\n\r\n					</li>\r\n					",671,965);
$z[4][4]['pagesize']="10";

?>