<?php
$z[0]=Array("field","",71,99);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",101,130);
$z[1][4]['name']="typename";
$z[2]=Array("field","",166,194);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n           <li><a class=\"pic\" href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\"><img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/><span class=\"countdown\">休闲西服01</span></a></li>\r\n		",329,618);
$z[3][4]['row']="4";
$z[3][4]['type']="image.";
$z[4]=Array("list","   \r\n				    <li>\r\n					    <div class=\"left_logo\"> [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' height='72' width='130'/></a>\"); [/field:array]</div>\r\n\r\n					</li>\r\n					",645,939);
$z[4][4]['pagesize']="10";
$z[5]=Array("list","   \r\n				    <li>\r\n					    <div class=\"left_logo\"> [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' height='72' width='130'/></a>\"); [/field:array]</div>\r\n						<div class=\"rightcon\">\r\n						    <div class=\"tit\"><a href=\"[field:arcurl/]\"><span class=\"bt\">[field:title/]</span></a><span class=\"date\">[field:pubdate function=\"GetDateTimeMK(@me)\"/]</span></div>\r\n							<div class=\"con\">[field:description/]...</div>\r\n						</div>\r\n					</li>\r\n					",977,1543);
$z[5][4]['pagesize']="10";
$z[6]=Array("arclist","\r\n      <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n      ",1573,1695);
$z[6][4]['titlelen']="60";
$z[6][4]['row']="8";

?>