<?php
$z[0]=Array("channel","\r\n      	<a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a>\r\n      	",926,1055);
$z[0][4]['type']="top";
$z[0][4]['row']="15";
$z[1]=Array("channelartlist","\r\n     <dl>\r\n        <dt>\r\n      	<a href='{dede:field name='typeurl'/}' >{dede:field name='typename'/}</a>\r\n        <dt>\r\n        <dd>\r\n            {dede:channel  type='son' row='10' }\r\n            <a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a>\r\n            {/dede:channel}\r\n        <dd>\r\n     </dl>\r\n     ",1150,1548);
$z[1][4]['typeid']="10";
$z[1][4]['type']="son";
$z[1][4]['row']="10";
$z[2]=Array("global","",1613,1645);
$z[2][4]['name']="cfg_templets_skin";

?>