<?php
$z[0]=Array("global","",307,339);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",411,443);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",558,590);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",1048,1083);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n                        linkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\r\n                        picarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n                        textarr[[field:global.autoindex/]] = \"[field:title function='html2text(@me)'/]\";\r\n                        ",4202,4543);
$z[4][4]['flag']="f";
$z[4][4]['row']="5";
$z[5]=Array("global","",5533,5563);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",5978,6008);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("type","\r\n                        <div class=\"title\"><strong>[field:typename/]</strong> <a class=\"more\" href='[field:typelink/]'>更多</a></div>\r\n                ",8053,8243);
$z[7][4]['typeid']="23";
$z[8]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\">\r\n                            <img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\" width=\"130\" height=\"72\" border=\"0\" /></a></li>\r\n                            ",8393,8741);
$z[8][4]['row']="10";
$z[8][4]['type']="image.";
$z[8][4]['typeid']="23";
$z[9]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\">●[field:title function='html2text(@me)' /]</a></li>\r\n                            ",8916,9117);
$z[9][4]['row']="10";
$z[9][4]['titlelen']="12";
$z[9][4]['typeid']="23";
$z[10]=Array("type","\r\n                         <li class=\"cur\" id='[field:id/]'><a>[field:typename/]</a></li>\r\n                        ",11619,11769);
$z[10][4]['typeid']="11";
$z[11]=Array("type","\r\n                         <li id='[field:id/]'><a>[field:typename/]</a></li>\r\n                        ",11843,11981);
$z[11][4]['typeid']="24";
$z[12]=Array("arclist","\r\n\r\n\r\n\r\n\r\n\r\n                        <li><a href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)' /]\">\r\n                            <img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\" width=\"130\" height=\"72\" border=\"0\" /></a></li>\r\n                      ",12141,12493);
$z[12][4]['row']="10";
$z[12][4]['type']="image.";
$z[12][4]['typeid']="11";

?>