<?php
$z[0]=Array("include","",560,595);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",633,676);
$z[1][4]['filename']="product_left.htm";
$z[2]=Array("list","\r\n				<li>\r\n\r\n                     <div class=\"proleftbox\">\r\n                                <img src=\"[field:litpic/]\"  width=\"255\" height=\"175\" />\r\n                            </div>\r\n                            <div class=\"rightinfo\">\r\n                                <p class=\"tit\"><a href=\"[field:arcurl /]\">[field:title/]</a></p>\r\n                                <p class=\"action\"><a class=\"rate\" href=\"#\"><s></s>好评： [field:scores/]</a><a class=\"popularity\" href=\"#\"><s></s>人气：[field:click/]</a></p>\r\n                                <p>价格：[field:trueprice/]元</p>\r\n                                <p class=\"pre\">详情： [field:description/]</p>\r\n                            </div>\r\n				</li>\r\n	",920,1678);
$z[2][4]['pagesize']="10";
$z[3]=Array("include","",10367,10404);
$z[3][4]['filename']="footer.htm";

?>