<?php
$z[0]=Array("include","",560,595);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",633,676);
$z[1][4]['filename']="product_left.htm";
$z[2]=Array("channelartlist","\r\n                <div class=\"mod\">\r\n                    <div class=\"title\"><strong><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></strong> <a class=\"more\" href=\"{dede:field name='typeurl'/}\">更多...</a></div>\r\n                    <div class=\"mod_con\">\r\n                        <ul class=\"list_item\">\r\n                            {dede:arclist titlelen='42' row='10'}    \r\n                             <li><a href=\"[field:arcurl /]\" class=\"pic\">\r\n                                 <img src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\" /><span class=\"countdown\">[field:title /]</span></a>\r\n                             </li>\r\n                            {/dede:arclist}\r\n                        </ul>\r\n                    </div>\r\n                </div>\r\n\r\n                ",760,1621);
$z[3]=Array("include","",11524,11561);
$z[3][4]['filename']="footer.htm";

?>