<?php
$z[0]=Array("arclist","\r\n            <dl class=\"good_list\">\r\n                <dt><a href=\"#\">\r\n                    <img src=\"[field:litpic/]\" width=\"115\" height=\"70\" /></a></dt>\r\n                <dd>\r\n                    <a class=\"name\" href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n                <dd>\r\n                    <a class=\"rate\" href=\"#\"><s></s>好评： 152</a></dd>\r\n                <dd>\r\n                    <a class=\"popularity\" href=\"#\"><s></s>人气：<script src=\"[field:phpurl/]/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script></a></dd>\r\n            </dl>\r\n            ",889,1578);
$z[0][4]['row']="10";
$z[0][4]['titlelen']="42";
$z[0][4]['orderby']="click";
$z[1]=Array("arclist","\r\n             <dl class=\"good_list\">\r\n                <dt><a href=\"#\">\r\n                    <img src=\"[field:litpic/]\" width=\"115\" height=\"70\" /></a></dt>\r\n                <dd>\r\n                    <a class=\"name\" href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n                <dd>\r\n                    <a class=\"rate\" href=\"#\"><s></s>好评： 152</a></dd>\r\n                <dd>\r\n                    <a class=\"popularity\" href=\"#\"><s></s>人气：<script src=\"[field:phpurl/]/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script></a></dd>\r\n            </dl>\r\n            ",1816,2499);
$z[1][4]['row']="10";
$z[1][4]['titlelen']="42";
$z[1][4]['flag']="c";

?>